import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The main documentation sidebar is auto-generated from the folder structure
 * under `docs/`. Ordering and category labels are controlled per-folder via
 * `_category_.json` files, and per-doc via `sidebar_position` frontmatter.
 *
 * This keeps each document in exactly one topic location while the persona
 * "reading path" pages (for-enthusiasts / for-developers / for-researchers)
 * cross-cut the tree with curated links.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
